---
name: License

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  license:
    name: License
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main

      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
